In [1]:
import torch
from models.EP_models import *

In [39]:
class TestingObj():
    def __init__(self):
        pass

param = TestingObj()

### param.num_classes
param.num_classes=100

### param.exit_block_pos
param.exit_block_pos = [1, 2, 3]


### param.ep
ep = TestingObj()
ep.stride = [8, 4, 2]
ep.conf_type = 'selection'
ep.selection_type = 'selection4'

param.ep = ep

In [40]:
model = EP_Model(BackboneNet='resnet18', EPNet='scan', param=param)

In [41]:
sample = torch.randn(1, 3, 32, 32)
result = model(sample)

In [42]:
len(result)

3

In [43]:
len(result[0]), len(result[1]), len(result[2])

(4, 4, 4)

In [44]:
result[2]

[tensor([[0.4805]]),
 tensor([[0.5153]]),
 tensor([[0.5188]]),
 tensor([[0.4242]])]